#Special tree types
#value is TRUE or FALSE

glow: TRUE
boom: TRUE
pumpkin: TRUE
melon: TRUE
mob: TRUE
cake: TRUE

#seed block for special tree types
#value is of type Material 

glowblock: GLOWSTONE
boomblock: TNT
pumpkinblock: PUMPKIN
melonblock: MELON_BLOCK
mobblock: MOB_SPAWNER
cakeblock: CAKE_BLOCK
lanternblock: SEA_LANTERN