name: GlowTree
main: net.moosecraft.GlowTree.GlowTree
version: 2.0
commands:
   glowtree:
      description: grow a tree over dirt over glowstone to grow more glowstone
      usage: "grow a tree over dirt over glowstone to grow more glowstone"