name: GlowTree
author: MooseOnTehLoose
main: net.moosecraft.GlowTree.GlowTree
version: 2.2-1.20.4
api-version: 1.20
commands:
   glowtree:
      description: grow a tree over dirt over glowstone to grow more glowstone
      usage: "instructions: https://github.com/MooseOnTehLoose/GlowTree"